package stdgo.io.fs;
private function get_errExist():stdgo.Error return stdgo._internal.io.fs.Fs_errExist.errExist;
