[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfunccancel.hx:15: characters 27-70

  15 |             var __tmp__ = _internal.context_test.Context_test_context.context.withCancel(stdgo.Go.asInterface(_ctx0)), _ctx1:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfunccancel.hx:20: characters 37-80

  20 |             @:check2r _ctx0._cancel(_internal.context_test.Context_test_context.context.canceled);
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfunctimeout.hx:15: characters 27-70

  15 |             var __tmp__ = _internal.context_test.Context_test_context.context.withTimeout(stdgo.Go.asInterface(_ctx0), (3600000000000000i64 : stdgo._internal.time.Time_duration.Duration)), _ctx1:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfunctimeout.hx:20: characters 37-80

  20 |             @:check2r _ctx0._cancel(_internal.context_test.Context_test_context.context.canceled);
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfuncafterfunc.hx:16: characters 26-69

  16 |             var _stop = (_internal.context_test.Context_test_context.context.afterFunc(stdgo.Go.asInterface(_ctx0), function():Void {
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfuncafterfunc.hx:23: characters 37-80

  23 |             @:check2r _ctx0._cancel(_internal.context_test.Context_test_context.context.canceled);
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfuncunregistercancel.hx:13: characters 23-66

  13 |         var __tmp__ = _internal.context_test.Context_test_context.context.withCancel(stdgo.Go.asInterface(_ctx0)), __0:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfuncunregistertimeout.hx:13: characters 23-66

  13 |         var __tmp__ = _internal.context_test.Context_test_context.context.withTimeout(stdgo.Go.asInterface(_ctx0), (3600000000000000i64 : stdgo._internal.time.Time_duration.Duration)), __0:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testcustomcontextafterfuncunregisterafterfunc.hx:13: characters 22-65

  13 |         var _stop = (_internal.context_test.Context_test_context.context.afterFunc(stdgo.Go.asInterface(_ctx0), function():Void {}) : () -> Bool);
     |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_testdeadlineexceededisneterror.hx:13: characters 63-106

  13 |             { _0 : (stdgo.Go.typeAssert((stdgo.Go.toInterface(_internal.context_test.Context_test_context.context.deadlineExceeded) : stdgo._internal.net.Net_error.Error)) : stdgo._internal.net.Net_error.Error), _1 : true };
     |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

      ->  /home/runner/haxe/versions/c4868e5/std/haxe/macro/Context.hx:504: characters 10-30

      504 |   return load("typeof", 1)(e);
          |          ^^^^^^^^^^^^^^^^^^^^
          | Called from here

      ->  stdgo/Go.macro.hx:653: characters 11-31

      653 |   var t = Context.typeof(expr);
          |           ^^^^^^^^^^^^^^^^^^^^
          | Called from here

      ->  ./_internal/context_test/Context_test_testdeadlineexceededisneterror.hx:13: characters 42-132

       13 |             { _0 : (stdgo.Go.typeAssert((stdgo.Go.toInterface(_internal.context_test.Context_test_context.context.deadlineExceeded) : stdgo._internal.net.Net_error.Error)) : stdgo._internal.net.Net_error.Error), _1 : true };
          |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here

[ERROR] ./_internal/context_test/Context_test_examplewithcancel.hx:50: characters 27-70

  50 |             var __tmp__ = _internal.context_test.Context_test_context.context.withCancel(_internal.context_test.Context_test_context.context.background()), _ctx:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_examplewithdeadline.hx:15: characters 27-70

  15 |             var __tmp__ = _internal.context_test.Context_test_context.context.withDeadline(_internal.context_test.Context_test_context.context.background(), _d?.__copy__()), _ctx:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_examplewithtimeout.hx:14: characters 27-70

  14 |             var __tmp__ = _internal.context_test.Context_test_context.context.withTimeout(_internal.context_test.Context_test_context.context.background(), (1000000i64 : stdgo._internal.time.Time_duration.Duration)), _ctx:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_examplewithvalue.hx:24: characters 21-64

  24 |         var _ctx = (_internal.context_test.Context_test_context.context.withValue(_internal.context_test.Context_test_context.context.background(), stdgo.Go.toInterface(_k), stdgo.Go.toInterface(("Go" : stdgo.GoString))) : stdgo._internal.context.Context_context.Context);
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_cond.hx:15: characters 31-74

  15 |                 var _stopf = (_internal.context_test.Context_test_context.context.afterFunc(_ctx, function():Void {
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_cond.hx:173: characters 43-86

 173 |                             var __tmp__ = _internal.context_test.Context_test_context.context.withTimeout(_internal.context_test.Context_test_context.context.background(), (1000000i64 : stdgo._internal.time.Time_duration.Duration)), _ctx:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

          | For function argument 'func'

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_connection.hx:17: characters 30-73

  17 |                 var _stop = (_internal.context_test.Context_test_context.context.afterFunc(_ctx, function():Void {
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_connection.hx:68: characters 27-70

  68 |             var __tmp__ = _internal.context_test.Context_test_context.context.withTimeout(_internal.context_test.Context_test_context.context.background(), (1000000i64 : stdgo._internal.time.Time_duration.Duration)), _ctx:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelfunc.CancelFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_merge.hx:15: characters 31-74

  15 |                 var __tmp__ = _internal.context_test.Context_test_context.context.withCancelCause(_ctx), _ctx:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel:stdgo._internal.context.Context_cancelcausefunc.CancelCauseFunc = __tmp__._1;
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_merge.hx:16: characters 30-73

  16 |                 var _stop = (_internal.context_test.Context_test_context.context.afterFunc(_cancelCtx, function():Void {
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_merge.hx:21: characters 29-72

  21 |                     _cancel(_internal.context_test.Context_test_context.context.canceled);
     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_merge.hx:24: characters 27-70

  24 |             var __tmp__ = _internal.context_test.Context_test_context.context.withCancelCause(_internal.context_test.Context_test_context.context.background()), _ctx1:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel1:stdgo._internal.context.Context_cancelcausefunc.CancelCauseFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_merge.hx:30: characters 27-70

  30 |             var __tmp__ = _internal.context_test.Context_test_context.context.withCancelCause(_internal.context_test.Context_test_context.context.background()), _ctx2:stdgo._internal.context.Context_context.Context = __tmp__._0, _cancel2:stdgo._internal.context.Context_cancelcausefunc.CancelCauseFunc = __tmp__._1;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

[ERROR] ./_internal/context_test/Context_test_exampleafterfunc_merge.hx:38: characters 74-117

  38 |             stdgo._internal.fmt.Fmt_println.println(stdgo.Go.toInterface(_internal.context_test.Context_test_context.context.cause(_mergedCtx)));
     |                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | Type not found : _internal.context_test.Context_test_context

      ->  /home/runner/haxe/versions/c4868e5/std/haxe/macro/Context.hx:504: characters 10-30

      504 |   return load("typeof", 1)(e);
          |          ^^^^^^^^^^^^^^^^^^^^
          | Called from here

      ->  stdgo/Go.macro.hx:653: characters 11-31

      653 |   var t = Context.typeof(expr);
          |           ^^^^^^^^^^^^^^^^^^^^
          | Called from here

      ->  ./_internal/context_test/Context_test_exampleafterfunc_merge.hx:38: characters 53-144

       38 |             stdgo._internal.fmt.Fmt_println.println(stdgo.Go.toInterface(_internal.context_test.Context_test_context.context.cause(_mergedCtx)));
          |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here

          | For function argument '_a'

