=== RUN  TestCustomContextAfterFuncCancel
Exception: :context.withCancel is not yet implemented
Called from stdgo._internal.testing.M_static_extension.run (./stdgo/_internal/testing/Testing_m_static_extension.hx line 34 column 17)
Called from _internal.context_test._Context_test_testcustomcontextafterfunccancel.Context_test_testcustomcontextafterfunccancel_Fields_.testCustomContextAfterFuncCancel (./_internal/context_test/Context_test_testcustomcontextafterfunccancel.hx line 61 column 21)

-- FAIL: TestCustomContextAfterFuncCancel

=== RUN  TestCustomContextAfterFuncTimeout
Exception: :context.withTimeout is not yet implemented
Called from stdgo._internal.testing.M_static_extension.run (./stdgo/_internal/testing/Testing_m_static_extension.hx line 34 column 17)
Called from _internal.context_test._Context_test_testcustomcontextafterfunctimeout.Context_test_testcustomcontextafterfunctimeout_Fields_.testCustomContextAfterFuncTimeout (./_internal/context_test/Context_test_testcustomcontextafterfunctimeout.hx line 61 column 21)

-- FAIL: TestCustomContextAfterFuncTimeout

=== RUN  TestCustomContextAfterFuncAfterFunc
Exception: :context.afterFunc is not yet implemented
Called from stdgo._internal.testing.M_static_extension.run (./stdgo/_internal/testing/Testing_m_static_extension.hx line 34 column 17)
Called from _internal.context_test._Context_test_testcustomcontextafterfuncafterfunc.Context_test_testcustomcontextafterfuncafterfunc_Fields_.testCustomContextAfterFuncAfterFunc (./_internal/context_test/Context_test_testcustomcontextafterfuncafterfunc.hx line 64 column 21)

-- FAIL: TestCustomContextAfterFuncAfterFunc

=== RUN  TestCustomContextAfterFuncUnregisterCancel
Exception: :context.withCancel is not yet implemented
Called from stdgo._internal.testing.M_static_extension.run (./stdgo/_internal/testing/Testing_m_static_extension.hx line 34 column 17)
Called from _internal.context_test._Context_test_testcustomcontextafterfuncunregistercancel.Context_test_testcustomcontextafterfuncunregistercancel_Fields_.testCustomContextAfterFuncUnregisterCancel (./_internal/context_test/Context_test_testcustomcontextafterfuncunregistercancel.hx line 4 column 23)
Called from stdgo._internal.context._Context_withcancel.Context_withcancel_Fields_.withCancel (./stdgo/_internal/context/Context_withcancel.hx line 2 column 204)

-- FAIL: TestCustomContextAfterFuncUnregisterCancel

=== RUN  TestCustomContextAfterFuncUnregisterTimeout
Exception: :context.withTimeout is not yet implemented
Called from stdgo._internal.testing.M_static_extension.run (./stdgo/_internal/testing/Testing_m_static_extension.hx line 34 column 17)
Called from _internal.context_test._Context_test_testcustomcontextafterfuncunregistertimeout.Context_test_testcustomcontextafterfuncunregistertimeout_Fields_.testCustomContextAfterFuncUnregisterTimeout (./_internal/context_test/Context_test_testcustomcontextafterfuncunregistertimeout.hx line 4 column 23)
Called from stdgo._internal.context._Context_withtimeout.Context_withtimeout_Fields_.withTimeout (./stdgo/_internal/context/Context_withtimeout.hx line 2 column 259)

-- FAIL: TestCustomContextAfterFuncUnregisterTimeout

=== RUN  TestCustomContextAfterFuncUnregisterAfterFunc
Exception: :context.afterFunc is not yet implemented
Called from stdgo._internal.testing.M_static_extension.run (./stdgo/_internal/testing/Testing_m_static_extension.hx line 34 column 17)
Called from _internal.context_test._Context_test_testcustomcontextafterfuncunregisterafterfunc.Context_test_testcustomcontextafterfuncunregisterafterfunc_Fields_.testCustomContextAfterFuncUnregisterAfterFunc (./_internal/context_test/Context_test_testcustomcontextafterfuncunregisterafterfunc.hx line 4 column 21)
Called from stdgo._internal.context._Context_afterfunc.Context_afterfunc_Fields_.afterFunc (./stdgo/_internal/context/Context_afterfunc.hx line 2 column 100)

-- FAIL: TestCustomContextAfterFuncUnregisterAfterFunc

=== RUN  TestDeadlineExceededIsNetError
DeadlineExceeded does not implement net.Error
Exception: __fail__
Called from stdgo._internal.testing.M_static_extension.run (./stdgo/_internal/testing/Testing_m_static_extension.hx line 34 column 17)
Called from _internal.context_test._Context_test_testdeadlineexceededisneterror.Context_test_testdeadlineexceededisneterror_Fields_.testDeadlineExceededIsNetError (./_internal/context_test/Context_test_testdeadlineexceededisneterror.hx line 9 column 32)
Called from local function #1 (./stdgo/_internal/testing/Testing_t_.hx line 43 column 88)
Called from stdgo._internal.testing.T_common_static_extension.fatal (./stdgo/_internal/testing/Testing_t_common_static_extension.hx line 77 column 9)
Called from stdgo._internal.testing.T_common_static_extension.failNow (./stdgo/_internal/testing/Testing_t_common_static_extension.hx line 118 column 9)

-- FAIL: TestDeadlineExceededIsNetError
