package stdgo._internal.internal.oserror;
import stdgo._internal.errors.Errors;
@:keep var __init_go2hx__ = {
        try {
            var __tmp__0 = stdgo._internal.internal.oserror.Oserror_errInvalid.errInvalid, __tmp__1 = stdgo._internal.internal.oserror.Oserror_errPermission.errPermission, __tmp__2 = stdgo._internal.internal.oserror.Oserror_errExist.errExist, __tmp__3 = stdgo._internal.internal.oserror.Oserror_errNotExist.errNotExist, __tmp__4 = stdgo._internal.internal.oserror.Oserror_errClosed.errClosed;
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
