# Module stdgo._internal.io.fs has compilation errors, please do not use:
```
[30;41m ERROR [0m stdgo/_internal/io/fs_test/Fs_test.hx:228: characters 9-11

 228 | [2m        [0m[1mfs[0m[2m.walkDir(_fileSystem, ("." : stdgo.GoString), function(_path:stdgo.GoString, _d:stdgo._internal.io.fs.Fs.DirEntry, _err:stdgo.Error):stdgo.Error {[0m
     |         [31m^^[0m
     | Unknown identifier : fs


```

